services:
  bento:
    container_name: bento
    image: bento_next
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.ts:/usr/share/nginx/html/config.ts
      - ./.env:/usr/share/nginx/html/.env
    ports:
      - 8888:8080
